### ISSUE TITLE
could not determine kind of name for C.av_packet_side_data_name

### ISSUE THREAD

**Issue by w495** [giorgisio/goav#1]
```(golang)
package main

import "github.com/giorgisio/goav/avformat"

func main() {
    avformat.Av_register_all()
}
```
For this I get:
```
[w495@95 goav]$ go build ./goavt1.go
# github.com/giorgisio/goav/avcodec
could not determine kind of name for C.av_packet_side_data_name
````

Where am I wrong?

**Comment by w495** [comment]
```
[w495@95 ~]$ go version
go version go1.4.2 linux/amd64
[w495@95 ~]$ uname -a
Linux 3.19.7-200.fc21.x86_64 #1 SMP Thu May 7 22:00:21 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by w495** [comment]
I guess this is not due to problems with ffmpeg itself. I try `github.com/3d0c/gmf` — all is fine.

What I should do to use goav?

**Comment by giorgisio** [comment]
You can temporarily set LD_LIBRARY_PATH. Major changes coming to the repo.

**Comment by coral** [comment]
@giorgisio same for me :( what do i need to do to fix it?

**Comment by giorgisio** [comment]
@w495 & @coral  I run into similar issue on a different machine. That was related to FFmpeg version. Could you try pulling the latest goav, and let me know if it works for you.
