### ISSUE TITLE
avcodec.Frame and avutil.Frame is the same type.

### ISSUE THREAD

**Issue by zwh8800** [giorgisio/goav#12]
Hi,
type avcodec.Frame and avutil.Frame is same (C.struct_AVFrame) in C. but in goav, is treated as different type. 
therefore, I must write as below:

``` go
frame := avutil.AvFrameAlloc()
codecFrame := (*avcodec.Frame)(unsafe.Pointer(frame))
codecContext.AvcodecDecodeAudio4(codecFrame, &gotFrame, packet)
```

**Comment by giorgisio** [comment]
@zwh8800 I haven't done proper tests on the last few merges. I've moved master back to a relatively working version while I go through the recent pull requests, and merges. I will also re-implement Travis CI. (Depends on how much time I get soon). In the mean time, running the examples (cd example && go run tutorial01.go) can point few but critical bugs.
