### ISSUE TITLE
Error after updated ffmpeg

### ISSUE THREAD

**Issue by khachung** [giorgisio/goav#24]
I've just updated ffmpeg and when I built my app, there were some errors:

```
# github.com/giorgisio/goav/avcodec
could not determine kind of name for C.AV_CODEC_ID_ADPCM_VIMA_DEPRECATED
could not determine kind of name for C.AV_CODEC_ID_BRENDER_PIX_DEPRECATED
could not determine kind of name for C.AV_CODEC_ID_ESCAPE130_DEPRECATED
could not determine kind of name for C.AV_CODEC_ID_EXR_DEPRECATED
could not determine kind of name for C.AV_CODEC_ID_G2M_DEPRECATED
could not determine kind of name for C.AV_CODEC_ID_HEVC_DEPRECATED
could not determine kind of name for C.AV_CODEC_ID_MVC1_DEPRECATED
could not determine kind of name for C.AV_CODEC_ID_MVC2_DEPRECATED
could not determine kind of name for C.AV_CODEC_ID_OPUS_DEPRECATED
could not determine kind of name for C.AV_CODEC_ID_PAF_AUDIO_DEPRECATED
could not determine kind of name for C.AV_CODEC_ID_PAF_VIDEO_DEPRECATED
could not determine kind of name for C.AV_CODEC_ID_PCM_S24LE_PLANAR_DEPRECATED
could not determine kind of name for C.AV_CODEC_ID_PCM_S32LE_PLANAR_DEPRECATED
could not determine kind of name for C.AV_CODEC_ID_SANM_DEPRECATED
could not determine kind of name for C.AV_CODEC_ID_SGIRLE_DEPRECATED
could not determine kind of name for C.AV_CODEC_ID_TAK_DEPRECATED
could not determine kind of name for C.AV_CODEC_ID_VP7_DEPRECATED
could not determine kind of name for C.AV_CODEC_ID_WEBP_DEPRECATED
```

I searched and found that from ffmpeg 3.0, it changed some things. Link: https://fossies.org/diffs/ffmpeg/2.8.6_vs_3.0/libavcodec/avcodec.h-diff.html

Thanks,

**Comment by rikuayanokozy** [comment]
See https://github.com/rikuayanokozy/goav/commit/664aa20cb7e0c8b0b4f6d8360fa73960f59a9172, it might helps.

**Comment by tab1293** [comment]
What was the solution to this problem? @rikuayanokozy that change did not fix this issue for me.

**Comment by rikuayanokozy** [comment]
@tab1293 which version of ffmpeg you are using?

**Comment by jaitaiwan** [comment]
@rikuayanokozy I can confirm that your branch didn't help. I'm personally using the head version of ffmpeg (606eac7)

**Comment by rikuayanokozy** [comment]
@jaitaiwan It works for me for ffmpeg 3.0(not 3.2), at least it can compile without error.

**Comment by jaitaiwan** [comment]
Ok cool. I'll give 3.0 a try

**Comment by rikuayanokozy** [comment]
@jaitaiwan @tab1293 
Due to project abandoned, the fork is stopped maintenance. I suggest using an active fork instead, check out the activity at https://github.com/giorgisio/goav/network
Also, there is a new project https://github.com/targodan/ffgopeg works well with FFMpeg 3.1.

**Comment by corebreaker** [comment]
Me i use **v4.0.2-2** of _libavcodec-dev_ and i have the same problem.
