### ISSUE TITLE
goav can not run

### ISSUE THREAD

**Issue by biij5698** [giorgisio/goav#32]
when i run the useage code,It report like this:
github.com/giorgisio/goav/avcodec
../github.com/giorgisio/goav/avcodec/codecs.go:57:48: could not determine kind of name for C.AV_CODEC_ID_ADPCM_VIMA_DEPRECATED

**Comment by corebreaker** [comment]
Me too, i used a recent version of libs (libavformat, libavcodecs, etc.) and i have this:
![image](https://user-images.githubusercontent.com/9797898/49869438-6e238e80-fe21-11e8-8f4b-4a6dbf35e6be.png)

**Comment by corebreaker** [comment]
Me too, i used a recent version of libs (libavformat, libavcodecs, etc.) and i have this:
![image](https://user-images.githubusercontent.com/9797898/49869510-9d3a0000-fe21-11e8-9191-90ee8954d6f6.png)

**Comment by pollythepug** [comment]
I can only build with ffmpeg-2.8.15. But running the tutorial01.go failed, error out with "Error: Couldn't open file."

**Comment by corebreaker** [comment]
@pollythepug, Yes it's due to another problem, here:
![image](https://user-images.githubusercontent.com/9797898/49984777-8b1fa500-ff7a-11e8-8ec8-0bd57c89b2d7.png)

after i tried to execute: `go run ./example/versions.go`

It seem that, the new version of the libraries removed symbols that were existed in previous versions.
I solved the problem, it compiles with less function and with deprecation warnings but it works.
I'll post a PR nearly.

**Comment by pollythepug** [comment]
Thank you @corebreaker .

**Comment by corebreaker** [comment]
I pushed a PR too, my solution can build, i hope it'll be merged soon.

**Comment by mybirthfather** [comment]
> @pollythepug, Yes it's due to another problem, here:
> ![image](https://user-images.githubusercontent.com/9797898/49984777-8b1fa500-ff7a-11e8-8ec8-0bd57c89b2d7.png)
> 
> after i tried to execute: `go run ./example/versions.go`
> 
> It seem that, the new version of the libraries removed symbols that were existed in previous versions.
> I solved the problem, it compiles with less function and with deprecation warnings but it works.
> 
> But the PR #31 should resolve the problem.

how did you d ？i have  the same problem

**Comment by corebreaker** [comment]
I solved the problem with PR #38
