### ISSUE TITLE
how can i run this project 

### ISSUE THREAD

**Issue by mybirthfather** [giorgisio/goav#39]
I compile the ffmpeg on windows and it succeed;but when i run the progect , it appears all th .h files can not be found ,hou should i set  here is errors pkg\src\github.com\giorgisio\goav\swscale\context.go:7:32: fatal error: libswscale/swscale.h: No such file or directory
compilation terminated. 
this is this  one of ths libs  i compiled
C:\Users\user>pkg-config libavutil --libs --cflags
-I/usr/local/include -L/usr/local/lib -lavutil -lm -luser32 -lbcrypt

**Comment by giorgisio** [comment]
Please refer the readme for steps.
