### ISSUE TITLE
 C ctructs member access

### ISSUE THREAD

**Issue by timhughes** [giorgisio/goav#45]
How do I access members in C ctructs that are returned by things like avcodec.CodecContext.AvCodecGetCodecDescriptor
like  CodecDescriptor.long_name  

If i just do a `fmt.Print(myDescriptor.long_name)` I get a `cannot refer to unexported field or method` error which is fair enough because it is lower-case.

I can see that there is data in there when I `fmt.Printf("`descriptor:%s", myDescriptor)` I get something like.

```descriptor:%!s(*avcodec.Descriptor=&{86018 1 0x7f7bf10e6a4b 0x7f7bf10e6a4f 2 <nil> 0x7f7bf1413340}) ```

Do I need to write some form of accessors code like the following. This doesn't work but it is my best attempt 

avcodec/descriptor_struct.go:
```
package avcodec

//#cgo pkg-config: libavcodec
//#include <libavcodec/avcodec.h>
import "C"

func (d *Descriptor) Name() string {
	return C.GoString(d.name)
}
func (d *Descriptor) LongName() string {
	return C.GoString(d.long_name)
}

```

**Comment by jviney** [comment]
Your example of `descriptor_struct.go` looks like it should work correctly. What's the error?

**Comment by timhughes** [comment]
I think i have worked it out now. I have been playing for the last couple of nights and written it up in a short blog post https://www.thegoldfish.org/2019/04/using-c-libraries-from-go/

**Comment by jviney** [comment]
Great. Make sure to be careful that anything allocated with `malloc` or `C.CString` is freed. The ownership of the `char*` pointers in your example is also a bit unclear.

With your example Go code, there is no way to free the memory held by the `APerson` struct and its `char*`. You would need to add something like a `void FreePerson(person **APerson)` to be able to do this, and call this from Go as appropriate.

Feel free to find me (jonathanv) in the [Golang Discord group](https://discord.gg/0f1SbxBZjYq9jLBk) if you need any help.

**Comment by timhughes** [comment]
Thanks
