### ISSUE TITLE
How do you iterate the streams ?

### ISSUE THREAD

**Issue by fzakaria** [giorgisio/goav#8]
The Context struct returns just the pointer to the stream which is the first element in the streams array.
Is there a way to just return a slice instead

**Comment by fzakaria** [comment]
sounds like I want to do something like:

```
func (ctxt *Context) Streams(i uint) *Stream {
	offset := (unsafe.Sizeof(unsafe.Pointer(ctxt.streams)) * uintptr(i))
	return (* Stream)(unsafe.Pointer(uintptr(unsafe.Pointer(ctxt.streams)) + offset ))
}
```

but this seems to return garbage data

**Comment by giorgisio** [comment]
I'm aware of the issues with the repo. I will attend to them when I get some time. Thanks for the pull requests.

**Comment by fzakaria** [comment]
@giorgisio  thanks for merging. I don't do much golang so please look over the changes if they are idiomatic. I'm just working on some Ffmpeg stuff and thought it would be nicer to work in Golang.
Thanks for the head start on the work here.

It would be cool if could figure out how to just return a slice https://github.com/golang/go/wiki/cgo#turning-c-arrays-into-go-slices

As that would be way simpler to work with.
I'll spend some more time on it.
