### ISSUE TITLE
encode h264, COM must not be in STA mode

### ISSUE THREAD

**Issue by msmarks** [giorgisio/goav#83]
I am using goav to encode h264 on windows 10.

```
enCodec := avcodec.AvcodecFindEncoder(avcodec.CodecId(avcodec.AV_CODEC_ID_H264))
enCodecCtx := enCodec.AvcodecAllocContext3()
enCodecCtx.SetTimebase(1, 1200000)
enCodecCtx.SetEncodeParams(640, 480, avcodec.AV_PIX_FMT_YUV)
err = enCodecCtx.AvcodecOpen2(enCodec, nil)
```

but it stop

[h264_mf @ 0000000028c60a40] COM must not be in STA mode

please help, thanks.

**Comment by Jenjen1324** [comment]
Seems to be some threading issue? Are you using some form of multithreading? goroutines?

**Comment by msmarks** [comment]
yes, goroutines, my fault.
